version: 2.1

jobs:
  loginmicroservices:

    working_directory: ~/BackEnd/loginmicroservices

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/mysql:latest
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: SEPTGROUP2

    steps:
      - checkout

      - run:
          name: Build
          command: ./mvnw -B -DskipTests clean package

  adminmicroservices:
      
      working_directory: ~/BackEnd/adminmicroservices
      
      docker:
        - image: circleci/openjdk:8-jdk-stretch
        - image: circleci/mysql:latest
          environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: SEPTGROUP2
  
      steps:
        - checkout

workflows:
  version: 2
  build-app:
    jobs:
      - loginmicroservices
      - adminmicroservices